name: Run Tests

#
# Create some files with script/new-artifact.sh and confirm they are properly packaged and uploaded
# as artifacts with the actions.
#
# This is tested on all OS platforms where we have hosted runners.
#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update_lower_adf_environments:
    runs-on: ubuntu-latest

    steps:
    - name: Run shell script
      run: ../script/new-artifact.sh
      shell: bash
