name: Update Lower ADF Environments

on:
  pull_request:
    branches:
      - main
jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
      name: Checkout new commit
      with:
        ref: ${{ github.head_ref }}
        path: ./
    - uses: actions/checkout@v3
      name: Checkout previous commit
      with:
        ref: main
        path: ./main
    - uses: actions/checkout@v3
      name: Checkout json file repo
      with:
        repository: calebu/kafka
        path: json-file-repo        
    - name: Run validator script
      env:
        VARS: ${{ toJson(vars.COMPULSORY_ADF_COMPONENTS) }}
      run: |
        merge_check=`python3 main/pipeline_test_script/pipeline_validator.py "$(find ./main -type f)" "$(find ./ -type f)" ./main ./ "$(echo $VARS)"` && if [ "$merge_check" != "" ]; then echo $merge_check;  exit 1; fi
      shell: bash
    - name: Run jira validator script
      run: |
        jira_check=`python3 ./main/script/jira_ticket_checker.py "${{ github.head_ref }}"` && if [ "$jira_check" != "" ]; then echo $jira_check;  exit 1; fi
      shell: bash
