name: Update Lower ADF Environments

#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        if [ "$PAT" -eq "the pat" ]
        then
          echo $PAT
        fi
        chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh
      shell: bash
