name: Update Lower ADF Environments

#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
<<<<<<< HEAD
        ls && python ./script/test_pipeline.py "${{ vars.REQUIRED_COMPONENTS }}" # && chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh ${{ vars.SSH_KEY_PHRASE }}
=======
        python ./script/test_pipeline.py '${{ vars.REQUIRED_COMPONENTS }}' && chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh ${{ vars.SSH_KEY_PHRASE }}
>>>>>>> b6edfedab430a551f3fe89df0a8d6b7d3cf9cb2b
      shell: bash
