name: Update Lower ADF Environments

#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: ls && pwd && chmod +x ./public/scripts/test.sh
      shell: bash
