name: Update Lower ADF Environments

#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo ${{ secrets }}
      shell: bash
    - name: Run script file
      run: echo ${{ var.PAT }}
      shell: bash
    - name: Run script file
      run: echo ${{ env.PAT }} && chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh ${{ secrets.PAT }}
      shell: bash
