name: Update Lower ADF Environments

#

on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main
jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: print body
      env:
#        BODY: ${{ toJson(github) }}
        BODY: ${{ github.event.pull_request.body }}
      run: echo "$BODY"
      shell: bash
    - uses: actions/checkout@v2
      name: Checkout previous commit
      with:
        ref: adf_documentation
        path: adf_documentation
    - uses: actions/checkout@v2
      name: Checkout current commit
      with:
        ref: main
        path: main
    - name: Run script file
      run: |
        python ./main/script/jira_ticket_checker.py "${{ github.event.pull_request.body }}" # && chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh ${{ vars.SSH_KEY_PHRASE }}
      shell: bash
