name: Update Lower ADF Environments

on:
  pull_request:
    branches:
      - main
jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: print body
      env:
        BODY: ${{ toJson(github) }}
        VARS: ${{ toJson(vars) }}
      run: echo "$BODY" && echo "$VARS"
      shell: bash
