name: Update Lower ADF Environments

#

on:
  pull_request:
    branches:
      - main
jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: print body
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "$BODY"
      shell: bash
    - uses: actions/checkout@v2
      name: Checout previous commit
      with:
        ref: adf_documentation
        path: adf_documentation
    - uses: actions/checkout@v2
      name: Checout current commit
      with:
        ref: main
        path: main
    - name: Run script file
      run: |
        ls && cat ./.github/workflows/script.yml && ls && python ./script/test_pipeline.py "${{ vars.REQUIRED_COMPONENTS }}" # && chmod +x ./script/adf_sync.sh && ./script/adf_sync.sh ${{ vars.SSH_KEY_PHRASE }}
      shell: bash
