name: Update Lower ADF Environments

on:
  pull_request:
    branches:
      - main
jobs:
  push_adf_changes:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: print body
      env:
        BODY: ${{ toJson(github) }}
        VARS: ${{ toJson(vars) }}
      run: echo "$BODY" && echo "$VARS"
      shell: bash
    - uses: actions/checkout@v3
      name: Checkout previous commit
      with:
        ref: main
        path: ./main
    - name: Run validator script
      run: |
        ls && merge_check=`python3 main/pipeline_test_script/pipeline_validator.py "$(find ./main -type f)" "$(find ./ -type f)" ./main ./ "${{ toJson(vars) }}"` && if [ "$merge_check" != "" ]; then echo $merge_check;  exit 1; fi
      shell: bash
    - name: Run script file
      run: |
        jira_check=`python3 ./main/script/jira_ticket_checker.py "${{ github.head_ref }}"` && if [ "$jira_check" != "" ]; then echo $jira_check;  exit 1; fi
      shell: bash
